# Generated by Django 4.1.1 on 2022-09-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.ImageField(default=0, unique=True, upload_to=''),
        ),
    ]
